server:
  port: 1111  # Keeping fadwa3's port

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bridge?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=Europe/Paris
    username: root
    password:  # Keep your actual password here
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  mail:                 # From maissa-notif
    host: smtp.gmail.com
    port: 587
    username: maissa.hermessi2@gmail.com
    password: grqt rxbl cfje jgch
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

# Python Scraper Configuration (from HEAD/fadwa3)
python:
  path: "venv/bin/python"
  scripts:
    competitions: "import_competitions.py"
    results: "import_requests.py"

# Scheduling Configuration (from HEAD/fadwa3)
scheduling:
  competitions:
    cron: "0 0 3 * * *" # Daily at 3 AM
    enabled: true

# Twilio Configuration (from maissa-notif)
twilio:
  account:
    sid: AC9eabe8927720dc4d0ef30aea4977993b
  auth:
    token: 8b7d06b4a684fb05108101cf4f497d70
  phone:
    number: +16085085729