server:
  port: 1111
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bridge?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # or validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
# Python Scraper Configuration
python:
  path: "venv/bin/python" # or "/path/to/venv/bin/python" if using virtualenv
  scripts:
    competitions: "import_competitions.py"
    results: "import_requests.py"

# Scheduling Configuration
scheduling:
  competitions:
    cron: "0 0 3 * * *" # Daily at 3 AM
    enabled: true